# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- checkout: self
  persistCredentials: 'true'
  clean: 'true'
- task: YodLabs.VariableTasks.SetVariablesWithCredentials.SetVariablesWithCredentials@0
  displayName: 'Github auth'
  inputs:
    ConnectionName: gh-push-tc-org
    userNameVarName: U
    passwordVarName: P  
- task: YodLabs.VariableTasks.SetVariablesWithCredentials.SetVariablesWithCredentials@0
  displayName: 'Netlify auth'
  inputs:
    ConnectionName: netlify-ehcache
    userNameVarName: NETLIFY_SITE_ID
    passwordVarName: NETLIFY_AUTH_TOKEN  
- task: Docker@0
  displayName: 'Jekyll and all Ruby steps'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    #containerCommand: 'sh -x -c "bundle install -V && bash -e get-deps.sh && JEKYLL_ENV=production jekyll build -V && bundle exec htmlproofer --only-4xx --empty-alt-ignore --check-html --checks-to-ignore ImageCheck --file-ignore \"/apidocs/,/generated/\" --log-level debug _site"'
    containerCommand: 'sh -x -c "bundle install -V && bash -e get-deps.sh && JEKYLL_ENV=production jekyll build -V "'
    detached: false
- bash: |
    set -e
    COMMIT=$(git rev-parse HEAD)
    sudo chown -R $(id -u):$(id -g) .
    rm -rf * .git*  # start clean
    git clone --single-branch -b gh-pages https://$U:$P@github.com/ehcache/ehcache.org-site remote-site
    cd remote-site
    echo "Target dir:"
    ls -l
    echo "Events in target:" ; ls -l events
    echo "Generated dir:"
    ls -l $BUILD_BINARIESDIRECTORY
    echo "Events in generated:" ; ls -l $BUILD_BINARIESDIRECTORY/events
    rsync -a --delete --exclude .git --exclude CNAME $BUILD_BINARIESDIRECTORY/ .
    echo "Result:"
    ls -l 
    echo "Events in result:" ; ls -l events
    git config --local user.name "autogen"
    git config --local user.email "autogen-noreply@no-reply.softwareag.com"
    echo Will push as $U
    git add -A .
    git status
    git commit -m "Autogenerated from #${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER} ${COMMIT}"
    git push https://$U:$P@github.com/ehcache/ehcache.org-site gh-pages
  displayName: 'Publish'
- bash: |
    echo disabled ; exit
    npm install netlify-cli
    $(npm bin)/netlify deploy -d $BUILD_BINARIESDIRECTORY
  displayName: 'Netlify Publish (disabled)'
